# Generated by Django 2.2.14 on 2021-01-22 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='product',
        ),
    ]
