# Generated by Django 2.2.14 on 2021-01-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='img',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
        migrations.AddField(
            model_name='cart',
            name='prd_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='online_shopping.product'),
            preserve_default=False,
        ),
    ]
