# Generated by Django 2.2.14 on 2021-01-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shopping', '0004_auto_20210124_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
