# Generated by Django 3.1.5 on 2021-01-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210127_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user1',
            new_name='id1',
        ),
    ]
