# Generated by Django 3.1.5 on 2021-01-27 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210127_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id1',
            new_name='user_id',
        ),
    ]
